#!/usr/bin/env python3
"""Codex 门的角色生成器：`agents/*.md` → `.codex/roles/<role>.toml` ＋ `.codex/config.toml` 注册段
＋ 产物账本 `.workframe/managed-files.json`。`workframe_door.py` 是唯一调用方，本模块只管生成与账本。

**契约（实测、两版一致）**：Codex 的子 agent 角色注册在项目 `.codex/config.toml` 的
`[agents.<name>]` 段，正文**必须**经 `config_file` 指向外置 role TOML；把 `developer_instructions`
内联进注册段会被**静默丢弃**（能注册、能 spawn、就是没有正文）。role TOML 里的 `name` 会被丢弃，
名字 = 注册段的表名。所以产物是两样：4 个 role TOML ＋ 4 段两行的注册。

**产物形态**
  - `.codex/roles/<role>.toml`：首行 `# DO NOT EDIT` 头标（说明来源与定制入口），
    `developer_instructions = '''<agents/<role>.md 去 frontmatter 的正文>'''`。
  - 用户定制：`.codex/roles/<role>.local.toml` 里写 `developer_instructions = "…"`，生成时**追加**在
    正文之后（`\\n\\n---\\n\\n` 分隔）。定制文件永不被生成器写，不进账本。
  - `.codex/config.toml`：只维护 marker 之间的一段（形态同 `.gitignore` 的 managed block），
    **段外字节一律不动**（不归一换行、不删空行——用户自写的部分原样保留）。段首是本插件的
    **项目级启用表** `[plugins."core@<市场名>"] enabled = true`（装机器同时把用户层置 `false`，插件只在
    跑过装机的项目里加载），其后是各角色的 `[agents.<role>]`。起点：
      文件不存在 → 新建，整份就是 managed 段；
      存在、**无 marker**（用户自己写的 `.codex/config.toml`）→ 末尾追加 managed 段并入账——
        账本只记段内 sha，用户段不参与任何判断；
      有 marker 且在账本、段内 sha 相符 → 替换段内（无启用表的旧形态段同样按「未被手改」替换）；
      有 marker 且在账本、**段首启用表被改成 `enabled = false`、其余与账本一致** → 「用户已关本项目
        Codex 门」的合法态：不改回，**生成前拒绝**，文案说明要重新开启就把它改回 `true` 后重跑；
      有 marker 且在账本、段内**其他任何一行**被手改 → **生成前拒绝**；
      有 marker 但**不在账本** → 分不清段内是不是被手改过，**生成前拒绝、不写任何文件**
        （`RoleError`，文案给出路：恢复账本，或把 marker 连同段一起删掉后重跑）。
    `config_file` 写 **相对 `.codex/` 的路径** `roles/<role>.toml`——项目随仓走，不写绝对路径
    （Codex 对相对路径按哪个基准解析由装机器的 `config/read` 回读核对；核不出即报出来）。
  - 账本 `<project>/.workframe/managed-files.json`：记录写过的每个文件（相对项目根）与 sha256。
    **重生成只动账本内的**；role TOML 存在但不在账本内 → 跳过并告警（`config.toml` 的规则见上）；
    在账本内但内容与账本 sha 不同（被手改）→ 跳过并告警、不覆盖——覆盖等于删掉用户的改动，
    删除权不给程序。要重生成先把该文件恢复到账本记录的内容或自行删除。账本进 git 是有意的
    （它是共享核心，`.workframe/state/` 才是运行态）。
    **比对口径**：记账与每一处比对（被手改、无操作、账本要不要重写）都经 `sha256_bytes`，先把 CRLF 归一成
    LF——git 检出时把 LF 转成 CRLF 只改行尾、不改内容，只差行尾的文件不算被手改，也不重写、不重记账本。
  - **整份语义判定**（`whole_file_problem`，**唯一实现**：装机器写任何东西之前的 `preflight()`、
    `generate()` 落盘前、`verify()` 与 `--check` 都用它）：把段拼进当前文件文本，对**拼接后的整份候选**
    做 TOML 解析，要求段内声明的每张表（启用表、每个 `agents.<role>`）在整份文件里的值**恰好等于**
    段单独解析出的值。不满足时三种说法：段外有同名声明（两张同名表 Codex 拒绝加载整份项目配置）、
    段后内容被段内表吸收、当前文件本身解析不了。
    **能力边界**：写在 END marker 之后、没有表头的键，按 TOML 语义属于段内**最后一张表**——Codex 或整份
    拒载、或把用户的值静默吞进段内的表；只解析「段外文本」给不出整份文件的真实语义，所以判的是整份。
    段外子表 `[plugins."core@<市场名>".x]` 按同一判据拒绝——严格是有意的（段内那张表必须恰好只有
    `enabled`）；只声明了别的插件的 `[plugins."other@mkt"]` 不受影响。

**确定性**：同输入逐字节同输出（LF、键序固定、不含时间戳——时间戳只在账本的 `written_at`）。

被 CLI 以同目录 import 方式使用：模块 import 无副作用；文件名用下划线。
"""

import hashlib
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

_SCRIPTS_DIR = str(Path(__file__).resolve().parent)
if _SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, _SCRIPTS_DIR)
from _state_io import RUNTIME_DIR  # noqa: E402  —— 中立运行态目录名只在 _state_io 定义一次

PLUGIN_NAME = "core"
ROLES_DIR_REL = Path(".codex") / "roles"
CONFIG_REL = Path(".codex") / "config.toml"
LEDGER_REL = Path(RUNTIME_DIR) / "managed-files.json"     # 项目 <RUNTIME_DIR>/，共享核心、进 git
LEDGER_SCHEMA = "workframe.managed-files.v1"
BLOCK_BEGIN = "# === Workframe managed (do not edit between markers) ==="
BLOCK_END = "# === End Workframe managed ==="
DO_NOT_EDIT = "# DO NOT EDIT — generated by workframe-door from core plugin agents/{role}.md (v{version}). 定制写 roles/{role}.local.toml"
ROLE_NAME_RE = re.compile(r"^[A-Za-z0-9_-]+$")
ENABLE_HEADER_RE = re.compile(r'^\[plugins\."(?P<id>(?:[^"\\]|\\.)+)"\]$')

# managed 段状态（`managed_block_state`）
BLOCK_ABSENT = "absent"
BLOCK_UNLEDGERED = "unledgered"
BLOCK_PRISTINE = "pristine"
BLOCK_USER_CLOSED = "user-closed"
BLOCK_EDITED = "edited"

# 预检失败的成因（`PreflightError.kind`）
KIND_OUTSIDE_DUP = "outside-duplicate"
KIND_ABSORBED = "absorbed-after-block"
KIND_UNPARSABLE = "unparsable"
KIND_USER_CLOSED = "user-closed"
KIND_BLOCK_EDITED = "block-edited"


class RoleError(Exception):
    """agent 定义解析不了：报错而不是跳过——跳过会让某个角色在 Codex 门下静默缺席。"""


class PreflightError(RoleError):
    """写任何文件之前判出的项目配置冲突；`kind` 是成因（见 `KIND_*`）。"""

    def __init__(self, kind, msg):
        super().__init__(msg)
        self.kind = kind


def plugin_id_for(marketplace):
    return f"{PLUGIN_NAME}@{marketplace}"


def _split_frontmatter(text):
    """(frontmatter 文本, 正文)；没有 frontmatter 时 ('', 全文)。行尾先归一。"""
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    if not text.startswith("---\n"):
        return "", text
    end = text.find("\n---\n", 4)
    if end < 0:
        raise RoleError("frontmatter 未闭合")
    return text[4:end], text[end + 5:]


def _fm_scalar(fm, key):
    """frontmatter 里一个标量或 `|` 块标量；不引 yaml 库（生成器不该多一个依赖）。"""
    lines = fm.split("\n")
    for i, ln in enumerate(lines):
        if not ln.startswith(key + ":"):
            continue
        rest = ln[len(key) + 1:].strip()
        if rest in ("|", "|-", ">", ">-"):
            block = []
            for nxt in lines[i + 1:]:
                if nxt.strip() == "" or nxt.startswith((" ", "\t")):
                    block.append(nxt.strip())
                else:
                    break
            return " ".join(b for b in block if b).strip()
        return rest.strip("\"'")
    return ""


def load_agents(agents_dir):
    """`agents/*.md` → 按角色名排序的 [(role, description, body)]。"""
    out = []
    for p in sorted(Path(agents_dir).glob("*.md")):
        fm, body = _split_frontmatter(p.read_text(encoding="utf-8-sig"))
        name = _fm_scalar(fm, "name") or p.stem
        if not ROLE_NAME_RE.match(name):
            raise RoleError(f"{p.name}: 角色名 {name!r} 不合法（只放行字母数字下划线连字符）")
        if not body.strip():
            raise RoleError(f"{p.name}: 正文为空——生成一个没有 developer_instructions 的角色等于没生成")
        out.append((name, _fm_scalar(fm, "description"), body.strip("\n")))
    if not out:
        raise RoleError(f"{agents_dir} 下没有任何 agent 定义")
    return out


def _toml_ml(text):
    """多行字面量字符串 `'''…'''`：正文里出现 `'''` 时退回基本字符串转义。"""
    if "'''" not in text:
        return "'''\n" + text + "\n'''"
    esc = text.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    return '"""\n' + esc + '\n"""'


def _toml_basic(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ") + '"'


def read_local_override(roles_dir, role):
    """`roles/<role>.local.toml` 里的 `developer_instructions`；没有返回 ''。只认这一个键。"""
    p = Path(roles_dir) / f"{role}.local.toml"
    if not p.is_file():
        return ""
    try:
        import tomllib
        data = tomllib.loads(p.read_text(encoding="utf-8-sig"))
        v = data.get("developer_instructions")
        return v.strip("\n") if isinstance(v, str) else ""
    except Exception as e:
        raise RoleError(f"{p.name} 解析失败: {e}")


def render_role(role, body, version, local_extra=""):
    text = body if not local_extra else body + "\n\n---\n\n" + local_extra
    return (DO_NOT_EDIT.format(role=role, version=version) + "\n"
            + "developer_instructions = " + _toml_ml(text) + "\n")


def render_block(roles, version, marketplace):
    """managed 段：头注释 → 本插件的项目级启用表（段首）→ 各角色注册。

    启用表放段首而不是段尾：END marker 之后的无表头键落进段内**最后一张表**，放段尾时它们会并进
    启用表（`enabled = false` 这类写法让 Codex 整份拒载），放段首时落点仍是最后一个 `[agents.*]`，
    与没有启用表时相同——吸收本身由整份语义判定（`whole_file_problem`）报出来。"""
    lines = [BLOCK_BEGIN,
             f"# 由 workframe-door 生成（core plugin v{version}）；角色正文在 roles/<role>.toml，"
             f"定制写 roles/<role>.local.toml 后重跑 workframe-door --codex",
             f"[plugins.{_toml_basic(plugin_id_for(marketplace))}]",
             "enabled = true"]
    for role, desc, _body in roles:
        lines += [f"[agents.{role}]",
                  f"description = {_toml_basic(desc or role)}",
                  f"config_file = \"roles/{role}.toml\""]
    lines.append(BLOCK_END)
    return "\n".join(lines) + "\n"


def splice_block(existing, block):
    """把 managed block 放进 `.codex/config.toml`：无文件 → block；无 marker → 末尾追加；
    有 marker → 只替换 BEGIN 到 END 那一段。**段外字节原样**：不归一换行、不吃段后的空行——
    用户自写的文件（可能是 CRLF、可能带 BOM）追加之后再跑一次必须逐字节不变。"""
    if existing is None:
        return block
    b, e = existing.find(BLOCK_BEGIN), existing.find(BLOCK_END)
    if b >= 0 and e > b:
        # 替换的是 [BEGIN, END] 这一闭区间；block 自带的尾换行不进去，END 之后原来是什么仍是什么
        return existing[:b] + block.rstrip("\n") + existing[e + len(BLOCK_END):]
    if b >= 0 or e >= 0:
        raise RoleError(".codex/config.toml 的 managed marker 不成对——不猜边界，请手工修复")
    sep = "" if not existing or existing.endswith("\n\n") else ("\n" if existing.endswith("\n") else "\n\n")
    return existing + sep + block


# ---- 整份语义判定（唯一实现）----

def _tail_has_bare_keys(text):
    """END marker 之后第一处有内容的行是不是无表头的键（它会被段内最后一张表吸收）。"""
    e = text.find(BLOCK_END)
    if e < 0:
        return False
    for ln in text[e + len(BLOCK_END):].splitlines():
        s = ln.strip()
        if not s or s.startswith("#"):
            continue
        return not s.startswith("[")
    return False


def _whole_msg(kind, detail, parsed=False):
    rel = CONFIG_REL.as_posix()
    if kind == KIND_ABSORBED:
        return (f"{rel} 的 END marker 之后有不带表头的键（{detail}）：按 TOML 语义它们属于 managed 段里最后一张表"
                f"——Codex 会整份拒载，或把你的值静默吞进段内的表。出路：给这些键加上它们所属的表头（例如 "
                f"`[features]`）后重跑")
    if kind == KIND_UNPARSABLE:
        return (f"{rel} 整份 TOML 解析失败（{detail}）——Codex 会连同角色注册与本插件的启用表一起丢掉项目层。"
                f"出路：先修文件再重跑")
    if parsed:
        # 整份能解析、只是段内声明的表多出了键或子表（段外的 `[plugins."core@<市场>".x]` / `[agents.<role>.x]`）：
        # 这不是「同一张表声明两次」，Codex 也照常加载——拒绝的理由是严格判据，不是 Codex 会炸
        return (f"{rel} 在 managed 段之外给段内声明的表多加了键或子表（{detail}）：段内每张表（本插件的启用表、各 "
                f"`[agents.<role>]`）在整份文件里必须恰好等于生成器写的样子——Codex 能加载这种写法，但门分不清那是不是"
                f"你的本意，严格是有意的。出路：去掉段外那处（或把这些键挪到别的表下）后重跑")
    return (f"{rel} 在 managed 段之外有与段内同名的声明（{detail}）：同一张表声明两次，Codex 会拒绝加载整份项目"
            f"配置（本插件与全部角色一起消失）。出路：去掉段外那处声明后重跑")


def _without_block(text):
    """把 [BEGIN, END] 那一段抠掉后的文本；没有成对 marker 返回 None。"""
    b, e = text.find(BLOCK_BEGIN), text.find(BLOCK_END)
    if b < 0 or e < b:
        return None
    return text[:b] + text[e + len(BLOCK_END):]


def whole_file_problem(full_text, block_text, current_text=None):
    """整份语义判定：返回 None，或 `(kind, 说明)`。

    `full_text` = 拼好段之后的整份候选（`verify()` 里就是当前文件）；`block_text` = 段本身；
    `current_text` = 拼接前的当前文件（None = 无文件），只用来先判「当前文件本身解析不了」。
    判据：`full_text` 解析成功，且段内声明的每张表在整份里的值恰好等于段单独解析出的值。

    **当前文件解析失败时先把段抠掉再解析一次**：已装项目（段已在文件里）再在段外写一张同名表，当前文件本身
    就解析不了——那不是「文件坏了」，是段内与段外的冲突，出路是去掉段外那处。抠掉段后仍解析失败才算文件本身坏了。
    """
    import tomllib
    if current_text is not None:
        try:
            tomllib.loads(current_text.lstrip("\ufeff"))
        except Exception as e:
            outside = _without_block(current_text)
            try:
                if outside is None:
                    raise ValueError("no managed block")
                tomllib.loads(outside.lstrip(chr(0xFEFF)))
            except Exception:
                return KIND_UNPARSABLE, _whole_msg(KIND_UNPARSABLE, str(e)[:160])
    try:
        want = tomllib.loads(block_text)
    except Exception as e:
        return KIND_UNPARSABLE, _whole_msg(KIND_UNPARSABLE, f"managed 段本身解析不了：{str(e)[:120]}")
    kind = KIND_ABSORBED if _tail_has_bare_keys(full_text) else KIND_OUTSIDE_DUP
    try:
        got = tomllib.loads(full_text.lstrip("\ufeff"))
    except Exception as e:
        return kind, _whole_msg(kind, str(e)[:160])
    bad = []
    for pid, val in (want.get("plugins") or {}).items():
        if (got.get("plugins") or {}).get(pid) != val:
            bad.append(f'plugins."{pid}" 整份里是 {(got.get("plugins") or {}).get(pid)!r}，段内是 {val!r}')
    for role, val in (want.get("agents") or {}).items():
        if (got.get("agents") or {}).get(role) != val:
            bad.append(f"agents.{role} 整份里多出 / 缺了键")
    if bad:
        return kind, _whole_msg(kind, "；".join(bad[:3]), parsed=True)
    return None


# ---- 账本 ----

def sha256_bytes(b):
    """账本 sha 的唯一口径：先把 CRLF 归一成 LF 再算。记账（`_record`）、被手改判定、无操作判定、账本要不要
    重写（`save_ledger`）都走这里——记账与比对不同口径时，内容里本身带 CRLF 的文件会被永远判成被手改。

    成因：生成物一律按 LF 写，账本与 `.codex/` 进 git；检出时 git 可能把 LF 转成 CRLF——Windows 上 Git for
    Windows 默认的 `core.autocrlf=true`，或任何平台上仓内 / 全局 attributes 写了 `eol=crlf`。换机器 clone、
    同机重新检出、`git worktree add` 都会触发。这种改动只动行尾、不动内容，按原始字节比就会把每一份这样检出的
    生成物都判成被手改。

    **宽度只到 CRLF 这一种**（git 检出只做这一种转换）：孤立的 `\\r`、文件头 BOM、删掉末尾换行、行尾空白都
    不归一，仍判被手改——它们不是检出造得出来的。

    内容不含 CR 时，结果与直接对原始字节算 sha256 相同：按原始字节记下的账，只要记账的内容不含 CR 就照旧有效。
    记账内容带 CR 只有一条来路——`.local.toml` 用基本字符串写了 `\\r\\n` 转义；那样按原始字节记下的账在这里
    对不上，该角色文件会被判被手改。"""
    return hashlib.sha256(b.replace(b"\r\n", b"\n")).hexdigest()


def load_ledger(project_dir):
    p = Path(project_dir) / LEDGER_REL
    if not p.is_file():
        return {"__schema__": LEDGER_SCHEMA, "__doc__": (
            "workframe 生成器写过的文件与其 sha256。重生成只动这里登记的文件；未登记的 role TOML 跳过，"
            "未登记的 .codex/config.toml 只追加 managed 段（段外不动）；登记但被手改的跳过不覆盖。"
            "卸载时只删这里登记且 sha 仍相符的文件。"), "files": {}}
    data = json.loads(p.read_text(encoding="utf-8-sig"))
    if not isinstance(data, dict) or not isinstance(data.get("files"), dict):
        raise RoleError(f"{LEDGER_REL} 不是预期形态——不覆盖，请手工修复")
    return data


def save_ledger(project_dir, ledger):
    """内容没变（只差行尾也算没变，口径见 `sha256_bytes`）就一个字节不写。检出成 CRLF 的账本若被重写成 LF，
    文件大小一变 `git status` 就直接报 ` M`（不比内容，`git diff` 却是空的）；每台机器、每次检出后第一次跑门
    都会这样。"""
    p = Path(project_dir) / LEDGER_REL
    data = (json.dumps(ledger, ensure_ascii=False, indent=2) + "\n").encode("utf-8")
    if p.is_file() and sha256_bytes(p.read_bytes()) == sha256_bytes(data):
        return
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_bytes(data)


def _put(project_dir, ledger, rel, content, kind, report):
    """按账本规则写一个文件；report 收 (rel, 动作, 说明)。返回是否写了。"""
    rel = Path(rel).as_posix()
    path = Path(project_dir) / rel
    data = content.encode("utf-8")
    entry = ledger["files"].get(rel)
    if path.exists():
        cur = path.read_bytes()
        if entry is None and kind == "managed-block":
            # 用户自写的 config.toml（无 marker）：追加 managed 段、段外字节原样。有 marker 而不在账本
            # 的形态已在 generate() 预检里拒绝，这里不会走到。
            try:
                cur_text = cur.decode("utf-8")
            except UnicodeDecodeError as e:
                raise RoleError(f"{rel} 不是 UTF-8 文本（{e}）——不动它，请自行检查后重跑")
            if _extract_block(cur_text) is not None:
                raise RoleError(f"{rel} 已有 managed 段但不在账本内——generate() 预检应已拒绝")
            data = splice_block(cur_text, content).encode("utf-8")
            path.write_bytes(data)
            _record(ledger, rel, content, kind)
            report.append((rel, "written", "已有你自写的 config.toml（无 managed 段）——只在末尾追加 managed 段，"
                                           "段外字节未动；账本只记这一段"))
            return True
        if entry is None:
            report.append((rel, "skipped", "已存在但不在账本内——不是本生成器写的，未动"))
            return False
        if kind == "managed-block":
            # 账本记的是段内 sha；段外用户内容不参与判断
            cur_block = _extract_block(cur.decode("utf-8", errors="replace"))
            if cur_block is not None and sha256_bytes(cur_block.encode("utf-8")) != entry.get("sha256"):
                report.append((rel, "skipped", "managed 段被手改——未覆盖；定制请写段外或 roles/<role>.local.toml"))
                return False
            new_text = splice_block(cur.decode("utf-8", errors="replace"), content)
            data = new_text.encode("utf-8")
            if sha256_bytes(data) == sha256_bytes(cur):     # 只差行尾也算无操作（口径见 sha256_bytes）
                report.append((rel, "unchanged", ""))     # 不重记：无操作时账本逐字节不变
                return False
        else:
            if sha256_bytes(cur) != entry.get("sha256"):
                report.append((rel, "skipped", "被手改——未覆盖；定制请写 roles/<role>.local.toml，"
                                                "要重生成先把它恢复到账本记录的内容"))
                return False
            if sha256_bytes(cur) == sha256_bytes(data):     # 同上
                report.append((rel, "unchanged", ""))
                return False
    elif kind == "managed-block":
        data = splice_block(None, content).encode("utf-8")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    _record(ledger, rel, content, kind)
    report.append((rel, "written", ""))
    return True


def _record(ledger, rel, content, kind):
    ledger["files"][rel] = {"sha256": sha256_bytes(content.encode("utf-8")), "kind": kind,
                            "written_at": datetime.now(timezone.utc).isoformat(timespec="seconds")}


def _extract_block(text):
    # 下一行的行尾归一仍在承重，不是 `sha256_bytes` 的重复：段内 sha 的比对两边都归一了，但返回值还直接喂给按行
    # 比对的 `_refuse_before_write`——它点名「不同的行」。CRLF 检出后只改段内一行时，不归一会把整段没改过的
    # 行一起列出来，把人引去看一整段没动过的内容。
    text = text.replace("\r\n", "\n")
    b, e = text.find(BLOCK_BEGIN), text.find(BLOCK_END)
    if b < 0 or e < b:
        return None
    return text[b:e + len(BLOCK_END)] + "\n"


def _flip_enable_to_true(block_text):
    """段首启用表的值若是 `false`，返回把那一行换成规范 `enabled = true` 后的段文本；否则 None。"""
    lines = block_text.split("\n")
    for i, ln in enumerate(lines[:-1]):
        if ln.startswith("[agents."):
            return None
        if ENABLE_HEADER_RE.match(ln.strip()):
            if re.fullmatch(r"\s*enabled\s*=\s*false\s*", lines[i + 1]):
                return "\n".join(lines[:i + 1] + ["enabled = true"] + lines[i + 2:])
            return None
    return None


def _commented_close_line(block_text):
    """段首启用表那一行若是带行尾注释的 `enabled = false  # …`，返回那一行（去首尾空白）；否则 None。
    门对这种写法仍判「被手改」（「已关」只认不带注释的写法，判法见 `managed_block_state`）——这里只给文案提示用。"""
    lines = block_text.split("\n")
    for i, ln in enumerate(lines[:-1]):
        if ln.startswith("[agents."):
            return None
        if ENABLE_HEADER_RE.match(ln.strip()):
            nxt = lines[i + 1]
            return nxt.strip() if re.fullmatch(r"\s*enabled\s*=\s*false\s*#.*", nxt) else None
    return None


def commented_close_line(project_dir):
    """项目 `.codex/config.toml` managed 段里「带行尾注释的 enabled = false」那一行；没有返回 None。"""
    p = Path(project_dir) / CONFIG_REL
    try:
        blk = _extract_block(p.read_text(encoding="utf-8", errors="replace")) if p.is_file() else None
    except OSError:
        return None
    return _commented_close_line(blk) if blk else None


def managed_block_state(project_dir, ledger=None):
    """`.codex/config.toml` managed 段此刻的状态：`BLOCK_ABSENT`（无文件或无 marker）/ `BLOCK_UNLEDGERED`
    （有 marker 不在账本）/ `BLOCK_PRISTINE`（段内 sha == 账本）/ `BLOCK_USER_CLOSED`（段首启用表是
    `enabled = false`、换回 `true` 后 sha == 账本）/ `BLOCK_EDITED`（其余任何手改）。
    **「用户已关」只有这一种判法**：把段内那一个值换回 `true` 后与账本记录的段逐字节相同。"""
    p = Path(project_dir) / CONFIG_REL
    if not p.is_file():
        return BLOCK_ABSENT
    blk = _extract_block(p.read_text(encoding="utf-8", errors="replace"))
    if blk is None:
        return BLOCK_ABSENT
    if ledger is None:
        ledger = load_ledger(project_dir)
    entry = ledger["files"].get(CONFIG_REL.as_posix())
    if entry is None:
        return BLOCK_UNLEDGERED
    want = entry.get("sha256")
    if sha256_bytes(blk.encode("utf-8")) == want:
        return BLOCK_PRISTINE
    flipped = _flip_enable_to_true(blk)
    if flipped is not None and sha256_bytes(flipped.encode("utf-8")) == want:
        return BLOCK_USER_CLOSED
    return BLOCK_EDITED


def block_enable_value(project_dir, plugin_id):
    """项目 managed 段里本插件启用表的 `enabled`：True / False / None（无段、无表或读不出）。只读段本身。"""
    try:
        import tomllib
        p = Path(project_dir) / CONFIG_REL
        blk = _extract_block(p.read_text(encoding="utf-8", errors="replace")) if p.is_file() else None
        if blk is None:
            return None
        entry = (tomllib.loads(blk).get("plugins") or {}).get(plugin_id)
        v = entry.get("enabled") if isinstance(entry, dict) else None
        return v if isinstance(v, bool) else None
    except Exception:
        return None


def _current_config_text(project_dir):
    p = Path(project_dir) / CONFIG_REL
    if not p.is_file():
        return None
    try:
        return p.read_bytes().decode("utf-8")
    except UnicodeDecodeError as e:
        raise RoleError(f"{CONFIG_REL.as_posix()} 不是 UTF-8 文本（{e}）——不动它，请自行检查后重跑")


def _refuse_before_write(project_dir, ledger, block):
    """写任何文件之前的四项判定（`preflight()` 与 `generate()` 共用）：有 marker 不在账本；段已被用户关闭；
    段内其他行被手改；拼上新段后的整份语义。任一命中抛错（`RoleError` / `PreflightError`）。"""
    _preflight_config(project_dir, ledger)
    state = managed_block_state(project_dir, ledger)
    rel = CONFIG_REL.as_posix()
    if state == BLOCK_USER_CLOSED:
        raise PreflightError(KIND_USER_CLOSED, (
            f"{rel} managed 段段首的启用表是 enabled = false——本项目的 Codex 门已被你关闭，门不会把它改回去。"
            f"要重新开启：把那一行改回 enabled = true 后重跑"))
    if state == BLOCK_EDITED:
        # 点名是哪几行：与本次将写入的段逐行比（头注释行带版本号，刚升级过时本来就不同，不列）
        cur_blk = _extract_block(_current_config_text(project_dir) or "") or ""
        rendered = set(block.split("\n"))
        odd = [ln.strip() for ln in cur_blk.split("\n")
               if ln.strip() and ln not in rendered and not ln.startswith("# 由 workframe-door 生成")]
        where = (("与本次将写入的段逐行比，不同的行：" + " / ".join(f"`{ln}`" for ln in odd[:3])
                  + (f" 等 {len(odd)} 行" if len(odd) > 3 else "")) if odd else "段内有行被删掉或挪了位置")
        hint = ("。若你是想关掉本项目的 Codex 门：只改值、不加注释（不带注释的 `enabled = false` 门才认作已关）"
                if _commented_close_line(cur_blk) else "")
        raise PreflightError(KIND_BLOCK_EDITED, (
            f"{rel} 的 managed 段被手改过（{where}）——不覆盖你的改动，"
            f"也不带着一个不知道长什么样的段继续装。出路：把段恢复原样（或把两处 marker 连同段一起删掉）后重跑；"
            f"角色定制写 roles/<role>.local.toml，其余配置写在段外{hint}"))
    current = _current_config_text(project_dir)
    prob = whole_file_problem(splice_block(current, block), block, current)
    if prob:
        raise PreflightError(*prob)


def preflight(project_dir, plugin_root, version, marketplace):
    """装机器在**写任何东西之前**（`codex plugin marketplace add` / `upgrade` 之前）调：通过返回 None，
    否则抛 `RoleError`（有 marker 不在账本）或 `PreflightError`（其余成因，见 `KIND_*`）。零写入。"""
    project_dir = Path(project_dir)
    roles = load_agents(Path(plugin_root) / "agents")
    _refuse_before_write(project_dir, load_ledger(project_dir), render_block(roles, version, marketplace))


def generate(project_dir, plugin_root, version, write=True, *, marketplace):
    """生成全部产物；返回 (report 列表, roles 列表)。`write=False` 只渲染不落盘（确定性自证用）。
    `marketplace` 决定段首启用表的插件 id（`core@<marketplace>`），必须显式给——写错 id 的启用表 Codex 静默不认。"""
    project_dir = Path(project_dir)
    roles = load_agents(Path(plugin_root) / "agents")
    roles_dir = project_dir / ROLES_DIR_REL
    rendered = {}
    for role, _desc, body in roles:
        rendered[(ROLES_DIR_REL / f"{role}.toml").as_posix()] = (
            render_role(role, body, version, read_local_override(roles_dir, role)), "role")
    rendered[CONFIG_REL.as_posix()] = (render_block(roles, version, marketplace), "managed-block")
    if not write:
        return rendered, roles
    ledger = load_ledger(project_dir)
    _refuse_before_write(project_dir, ledger, rendered[CONFIG_REL.as_posix()][0])
    report = []
    for rel, (content, kind) in rendered.items():
        _put(project_dir, ledger, rel, content, kind, report)
    save_ledger(project_dir, ledger)
    return report, roles


def _preflight_config(project_dir, ledger):
    """写任何文件之前先判 `.codex/config.toml` 的起点：有 managed 段却不在账本内 → 拒绝。
    此时分不清段内是「上次生成的原样」还是「被手改过」，覆盖可能删掉用户的改动、跳过则装到
    步 8 才以「角色未被读到」失败——两边都不对，所以在写 role TOML 之前就停。"""
    rel = CONFIG_REL.as_posix()
    p = Path(project_dir) / rel
    if rel in ledger["files"] or not p.is_file():
        return
    if _extract_block(p.read_text(encoding="utf-8", errors="replace")) is not None:
        raise RoleError(f"{rel} 已有 Workframe managed 段，但账本 {LEDGER_REL.as_posix()} 没有登记它"
                        f"（账本丢了？文件从别的项目复制来的？）——未写任何文件。处置：恢复账本，"
                        f"或把两处 marker 连同段内内容一起删掉后重跑 workframe-door --codex")


def verify(project_dir):
    """`--check` 用：账本里每个文件都在且 sha 相符（段首启用表被用户改成 false 的「已关」态不算问题）；
    `.codex/config.toml` 的 managed 段登记了哪些角色、各自 `config_file` 是否存在；整份语义判定
    （与写盘前同一个 `whole_file_problem`）。返回问题列表（空 = 过）。"""
    project_dir = Path(project_dir)
    problems = []
    try:
        ledger = load_ledger(project_dir)
    except Exception as e:
        return [f"账本读取失败: {e}"]
    if not ledger["files"]:
        return [f"{LEDGER_REL.as_posix()} 没有登记任何文件——角色尚未生成（跑 workframe-door --codex）"]
    for rel, entry in ledger["files"].items():
        p = project_dir / rel
        if not p.exists():
            problems.append(f"{rel}: 账本登记了但文件不存在")
            continue
        if entry.get("kind") == "managed-block":
            blk = _extract_block(p.read_text(encoding="utf-8", errors="replace"))
            if blk is None:
                problems.append(f"{rel}: managed 段缺失")
            elif sha256_bytes(blk.encode("utf-8")) != entry.get("sha256") \
                    and managed_block_state(project_dir, ledger) != BLOCK_USER_CLOSED:
                cl = _commented_close_line(blk)
                problems.append(f"{rel}: managed 段与账本不符（被手改）"
                                + (f"——段首启用表那一行是 `{cl}`：只改值、不加注释才算「已关」" if cl else ""))
        elif sha256_bytes(p.read_bytes()) != entry.get("sha256"):
            problems.append(f"{rel}: 内容与账本不符（被手改）")
    cfg = project_dir / CONFIG_REL
    registered = {}
    if cfg.is_file():
        text = cfg.read_text(encoding="utf-8", errors="replace")
        for m in re.finditer(r'^\[agents\.([A-Za-z0-9_-]+)\]\s*$', text, re.M):
            tail = text[m.end():].split("\n[", 1)[0]
            cf = re.search(r'^config_file\s*=\s*"([^"]+)"', tail, re.M)
            if not cf:
                problems.append(f"[agents.{m.group(1)}] 缺 config_file——正文内联会被 Codex 静默丢弃")
            elif not (cfg.parent / cf.group(1)).is_file():
                problems.append(f"[agents.{m.group(1)}] config_file 指向的 {cf.group(1)} 不存在")
            else:
                registered[m.group(1)] = cf.group(1)
        # 整份语义：段外有同名声明 / 段后键被段内表吸收 / 整份解析不了——Codex 丢掉的是整个项目层（角色注册
        # 与启用表一起没了），而装机器只在回读时才看得到——这里先判，红在写信任之前
        blk = _extract_block(text)
        prob = (whole_file_problem(text, blk, text) if blk is not None
                else whole_file_problem(text, "", text))
        if prob:
            problems.append(prob[1])
    # 账本里每个已生成的角色都必须已注册——否则就是「role TOML 写了、注册段没写」的半装态
    for rel, entry in ledger["files"].items():
        if entry.get("kind") != "role":
            continue
        role = Path(rel).stem
        want = f"roles/{role}.toml"
        if registered.get(role) != want:
            problems.append(f"角色 {role} 已生成（{rel}）但 {CONFIG_REL.as_posix()} 没有 [agents.{role}] "
                            f"config_file = \"{want}\"——注册段没写进去，Codex 看不到这个角色")
    return problems
